### ISSUE TITLE
Namespace package modules.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [BrendoCosta/gwr#1]
In the Hex ecosystem, packages are not implicitly namespaced by the package name so it can be easy to run into collisions. Could you consider name spacing all the modules in this package under `gwr/` or `web_assembly/` or something similar?

**Comment by BrendoCosta** [comment]
> In the Hex ecosystem, packages are not implicitly namespaced by the package name so it can be easy to run into collisions. Could you consider name spacing all the modules in this package under `gwr/` or `web_assembly/` or something similar?

Hi @hayleigh-dot-dev ! Sorry for the late reply! I've taken this issue into account and am fixing it in 4881766 commit. Thanks for letting me know!
